services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CrawlerBundle\:
    resource: '../../../CrawlerBundle/*'
    exclude: '../../../CrawlerBundle/[Document]'

#  CrawlerBundle\Command\Crawler:
#      tags:
#        - { name: 'console.command', command: 'app:crawler'}
#      calls:
#        - method: setDocumentManager
#          arguments:
#            - '@doctrine_mongodb.odm.document_manager'
